
[airdrop_spawn_setting]
	#Range: 10 ~ 10000
	AIRDROP_SPREAD_RANGE = 10
	#Airdrop spawn interval in tick.
	#Range: 100 ~ 720000
	AIRDROP_SPAWN_INTERVAL = 864000
	#Airdrop despawn time in tick.
	#Range: 100 ~ 8760000
	AIRDROP_DESPAWN_TIME = 518400

[airdrop_type_weight]
	#Range: 0 ~ 10000
	MEDIC_AIRDROP_WEIGHT = 5
	#Range: 0 ~ 10000
	AMMO_AIRDROP_WEIGHT = 3
	#Range: 0 ~ 10000
	NO_AIRDROP_WEIGHT = 2